#!/usr/bin/env python3
"""Generates assets/sounds/*.wav and hooks/builtins.ts for the sound-board mod.

Stdlib only. `python scripts/make-sounds.py` writes both; `--check` reopens every
file with `wave` and checks the format, the length and the generated table.
"""
import argparse
import math
import os
import struct
import sys
import wave

RATE = 44100
PEAK = 0.45
EDGE = 0.008  # linear attack and release per segment, seconds
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOUNDS = os.path.join(ROOT, 'assets', 'sounds')
BUILTINS_TS = os.path.join(ROOT, 'hooks', 'builtins.ts')


def tri(phase):
    return 2 / math.pi * math.asin(math.sin(phase))


def tone(freq, dur, shape='sine', decay=None):
    n = int(RATE * dur)
    out = []
    for i in range(n):
        t = i / RATE
        p = 2 * math.pi * freq * t
        v = tri(p) if shape == 'triangle' else math.sin(p)
        if decay:
            v *= math.exp(-t / decay)
        out.append(v)
    return envelope(out)


def envelope(samples):
    n = len(samples)
    edge = min(int(RATE * EDGE), n // 2)
    for i in range(edge):
        g = i / edge
        samples[i] *= g
        samples[n - 1 - i] *= g
    return samples


def silence(dur):
    return [0.0] * int(RATE * dur)


def mix(*parts):
    n = max(len(p) for p in parts)
    return [sum(p[i] for p in parts if i < len(p)) / len(parts) for i in range(n)]


def buzz():
    n = int(RATE * 0.45)
    out = []
    for i in range(n):
        t = i / RATE
        v = sum(math.sin(2 * math.pi * 110 * k * t) / k for k in (1, 3, 5, 7))
        v *= 0.6 + 0.4 * math.sin(2 * math.pi * 12 * t)
        out.append(v / 2)
    return envelope(out)


def sweep(f0, f1, dur):
    n = int(RATE * dur)
    out, phase = [], 0.0
    for i in range(n):
        f = f0 + (f1 - f0) * i / n
        phase += 2 * math.pi * f / RATE
        out.append(math.sin(phase))
    return envelope(out)


def build():
    return {
        'agent-spawn': ('rise', tone(660, 0.08) + silence(0.02) + tone(880, 0.10)),
        'agent-done': ('fall', tone(880, 0.10) + tone(660, 0.10)),
        'agent-failed': ('drop', tone(330, 0.15, 'triangle') + tone(220, 0.25, 'triangle')),
        'permission-ask': ('blips', tone(1047, 0.06) + silence(0.05) + tone(1047, 0.06) + silence(0.05) + tone(1047, 0.06)),
        'permission-denied': ('buzz', buzz()),
        'turn-done': ('chime', mix(tone(1319, 0.6, decay=0.18), tone(1760, 0.6, decay=0.18))),
        'turn-failed': ('sink', tone(440, 0.175, 'triangle') + tone(415, 0.175, 'triangle')),
        'compact': ('sweep', sweep(1200, 400, 0.3)),
        'session-end': ('descend', tone(784, 0.12) + tone(659, 0.12) + tone(523, 0.12)),
        'long-tool': ('pings', tone(988, 0.125, decay=0.04) + tone(988, 0.125, decay=0.04)),
        'pop': ('pop', tone(440, 0.1, decay=0.025)),
        'bell': ('bell', mix(tone(523, 0.6, decay=0.2), tone(1046, 0.6, decay=0.2))),
        'tick': ('tick', tone(2000, 0.1, decay=0.012)),
    }


def write_wav(path, samples):
    peak = max(abs(s) for s in samples) or 1
    scale = PEAK / peak
    data = b''.join(struct.pack('<h', int(max(-1, min(1, s * scale)) * 32767)) for s in samples)
    with wave.open(path, 'wb') as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(data)


def generate():
    os.makedirs(SOUNDS, exist_ok=True)
    rows = []
    for name, (label, samples) in build().items():
        path = os.path.join(SOUNDS, name + '.wav')
        write_wav(path, samples)
        with open(path, 'rb') as f:
            header = list(f.read(44))
        ms = round(len(samples) * 1000 / RATE)
        rows.append(
            "  { name: '%s', file: '%s.wav', label: '%s', durationMs: %d, header: [%s] },"
            % (name, name, label, ms, ','.join(str(b) for b in header))
        )
    with open(BUILTINS_TS, 'w', newline='\n') as f:
        f.write('// GENERATED by scripts/make-sounds.py; do not edit\n')
        f.write('export type Builtin = { name: string; file: string; label: string; durationMs: number; header: readonly number[] }\n')
        f.write('export const BUILTINS: readonly Builtin[] = [\n' + '\n'.join(rows) + '\n]\n')
    print('wrote %d sounds and hooks/builtins.ts' % len(rows))


def check():
    bad = 0
    names = build().keys()
    for name in names:
        path = os.path.join(SOUNDS, name + '.wav')
        try:
            with wave.open(path, 'rb') as w:
                rate, ch, width, frames = w.getframerate(), w.getnchannels(), w.getsampwidth(), w.getnframes()
            secs = frames / rate
            ok = rate == RATE and ch == 1 and width == 2 and 0.1 <= secs <= 0.6 + 1e-9 and os.path.getsize(path) == 44 + frames * 2
            print('%-20s %s  %.3fs  %d bytes' % (name, 'ok' if ok else 'BAD', secs, os.path.getsize(path)))
            bad += 0 if ok else 1
        except Exception as err:  # noqa: BLE001
            print('%-20s BAD  %s' % (name, err))
            bad += 1
    with open(BUILTINS_TS, encoding='utf-8') as f:
        table = f.read()
    for name in names:
        if "name: '%s'" % name not in table:
            print('builtins.ts is missing', name)
            bad += 1
    print('check: %s' % ('FAILED (%d)' % bad if bad else 'all %d sounds ok' % len(list(names))))
    return 1 if bad else 0


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    if args.check:
        sys.exit(check())
    generate()
