// GENERATED by scripts/make-sounds.py; do not edit
export type Builtin = { name: string; file: string; label: string; durationMs: number; header: readonly number[] }
export const BUILTINS: readonly Builtin[] = [
  { name: 'agent-spawn', file: 'agent-spawn.wav', label: 'rise', durationMs: 200, header: [82,73,70,70,12,69,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,232,68,0,0] },
  { name: 'agent-done', file: 'agent-done.wav', label: 'fall', durationMs: 200, header: [82,73,70,70,12,69,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,232,68,0,0] },
  { name: 'agent-failed', file: 'agent-failed.wav', label: 'drop', durationMs: 400, header: [82,73,70,70,244,137,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,208,137,0,0] },
  { name: 'permission-ask', file: 'permission-ask.wav', label: 'blips', durationMs: 280, header: [82,73,70,70,156,96,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,120,96,0,0] },
  { name: 'permission-denied', file: 'permission-denied.wav', label: 'buzz', durationMs: 450, header: [82,73,70,70,46,155,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,10,155,0,0] },
  { name: 'turn-done', file: 'turn-done.wav', label: 'chime', durationMs: 600, header: [82,73,70,70,220,206,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,184,206,0,0] },
  { name: 'turn-failed', file: 'turn-failed.wav', label: 'sink', durationMs: 350, header: [82,73,70,70,184,120,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,148,120,0,0] },
  { name: 'compact', file: 'compact.wav', label: 'sweep', durationMs: 300, header: [82,73,70,70,128,103,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,92,103,0,0] },
  { name: 'session-end', file: 'session-end.wav', label: 'descend', durationMs: 360, header: [82,73,70,70,44,124,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,8,124,0,0] },
  { name: 'long-tool', file: 'long-tool.wav', label: 'pings', durationMs: 250, header: [82,73,70,70,68,86,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,32,86,0,0] },
  { name: 'pop', file: 'pop.wav', label: 'pop', durationMs: 100, header: [82,73,70,70,152,34,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,116,34,0,0] },
  { name: 'bell', file: 'bell.wav', label: 'bell', durationMs: 600, header: [82,73,70,70,220,206,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,184,206,0,0] },
  { name: 'tick', file: 'tick.wav', label: 'tick', durationMs: 100, header: [82,73,70,70,152,34,0,0,87,65,86,69,102,109,116,32,16,0,0,0,1,0,1,0,68,172,0,0,136,88,1,0,2,0,16,0,100,97,116,97,116,34,0,0] },
]
