@echo off
rem Builds gba-cc.exe (mGBA 0.10.5, GBA core only) with MSVC into ..\bin (or the folder given).
rem Generated by native\gen_build.py from mGBA's CMake source lists; edit that, not this.
setlocal
set OUT=%~1
if "%OUT%"=="" set OUT=%~dp0..\bin
rem A long inherited PATH overflows vcvars; start it from a clean one.
set "PATH=%SystemRoot%\system32;%SystemRoot%;%ProgramFiles(x86)%\Microsoft Visual Studio\Installer"
call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" >nul || exit /b 1
if not exist "%~dp0obj" mkdir "%~dp0obj"
if not exist "%OUT%" mkdir "%OUT%"
pushd "%~dp0obj"
set MGBA_DEFS=-DBUILD_STATIC -DM_CORE_GBA -DMINIMAL_CORE=1 -DDISABLE_THREADING -D_WIN32_WINNT=0x0600 -DNOMINMAX -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_WARNINGS -DNDEBUG
set MGBA_FLAGS=-nologo -c -O2 -MT -std:c11 -W0 /MP /wd4003 /wd4244 /wd4146 /wd4267 /Zc:preprocessor-
set INC=-I..\mgba-shim -I..\mgba\include -I..\mgba\src
if not exist mgba\src_arm mkdir mgba\src_arm
if not exist mgba\src_core mkdir mgba\src_core
if not exist mgba\src_gb mkdir mgba\src_gb
if not exist mgba\src_gba mkdir mgba\src_gba
if not exist mgba\src_gba_cart mkdir mgba\src_gba_cart
if not exist mgba\src_gba_cheats mkdir mgba\src_gba_cheats
if not exist mgba\src_gba_renderers mkdir mgba\src_gba_renderers
if not exist mgba\src_gba_sio mkdir mgba\src_gba_sio
if not exist mgba\src_util mkdir mgba\src_util
if not exist mgba\src_util_vfs mkdir mgba\src_util_vfs
if not exist mgba\src_platform_windows mkdir mgba\src_platform_windows
if not exist mgba\src_third_party_inih mkdir mgba\src_third_party_inih
if not exist mgba\gba_pane mkdir mgba\gba_pane
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_arm\ ^
  ..\mgba\src\arm\arm.c ..\mgba\src\arm\decoder-arm.c ..\mgba\src\arm\decoder.c ..\mgba\src\arm\decoder-thumb.c ..\mgba\src\arm\isa-arm.c ..\mgba\src\arm\isa-thumb.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_core\ ^
  ..\mgba\src\core\bitmap-cache.c ..\mgba\src\core\cache-set.c ..\mgba\src\core\cheats.c ..\mgba\src\core\config.c ..\mgba\src\core\core.c ..\mgba\src\core\directories.c ^
  ..\mgba\src\core\input.c ..\mgba\src\core\interface.c ..\mgba\src\core\library.c ..\mgba\src\core\lockstep.c ..\mgba\src\core\log.c ..\mgba\src\core\map-cache.c ^
  ..\mgba\src\core\mem-search.c ..\mgba\src\core\rewind.c ..\mgba\src\core\serialize.c ..\mgba\src\core\sync.c ..\mgba\src\core\thread.c ..\mgba\src\core\tile-cache.c ^
  ..\mgba\src\core\timing.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_gb\ ^
  ..\mgba\src\gb\audio.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_gba\ ^
  ..\mgba\src\gba\audio.c ..\mgba\src\gba\bios.c ..\mgba\src\gba\cheats.c ..\mgba\src\gba\core.c ..\mgba\src\gba\dma.c ..\mgba\src\gba\gba.c ^
  ..\mgba\src\gba\hle-bios.c ..\mgba\src\gba\input.c ..\mgba\src\gba\io.c ..\mgba\src\gba\memory.c ..\mgba\src\gba\overrides.c ..\mgba\src\gba\savedata.c ^
  ..\mgba\src\gba\serialize.c ..\mgba\src\gba\sharkport.c ..\mgba\src\gba\sio.c ..\mgba\src\gba\timer.c ..\mgba\src\gba\video.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_gba_cart\ ^
  ..\mgba\src\gba\cart\ereader.c ..\mgba\src\gba\cart\gpio.c ..\mgba\src\gba\cart\matrix.c ..\mgba\src\gba\cart\vfame.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_gba_cheats\ ^
  ..\mgba\src\gba\cheats\codebreaker.c ..\mgba\src\gba\cheats\gameshark.c ..\mgba\src\gba\cheats\parv3.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_gba_renderers\ ^
  ..\mgba\src\gba\renderers\cache-set.c ..\mgba\src\gba\renderers\common.c ..\mgba\src\gba\renderers\software-bg.c ..\mgba\src\gba\renderers\software-mode0.c ..\mgba\src\gba\renderers\software-obj.c ..\mgba\src\gba\renderers\video-software.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_gba_sio\ ^
  ..\mgba\src\gba\sio\gbp.c ..\mgba\src\gba\sio\joybus.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_util\ ^
  ..\mgba\src\util\circle-buffer.c ..\mgba\src\util\configuration.c ..\mgba\src\util\crc32.c ..\mgba\src\util\formatting.c ..\mgba\src\util\gbk-table.c ..\mgba\src\util\hash.c ^
  ..\mgba\src\util\string.c ..\mgba\src\util\table.c ..\mgba\src\util\vfs.c ..\mgba\src\util\convolve.c ..\mgba\src\util\export.c ..\mgba\src\util\patch.c ^
  ..\mgba\src\util\patch-fast.c ..\mgba\src\util\patch-ips.c ..\mgba\src\util\patch-ups.c ..\mgba\src\util\ring-fifo.c ..\mgba\src\util\text-codec.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_util_vfs\ ^
  ..\mgba\src\util\vfs\vfs-mem.c ..\mgba\src\util\vfs\vfs-fifo.c ..\mgba\src\util\vfs\vfs-fd.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_platform_windows\ ^
  ..\mgba\src\platform\windows\vfs-w32.c ..\mgba\src\platform\windows\memory.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\src_third_party_inih\ ^
  ..\mgba\src\third-party\inih\ini.c || goto :fail
cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fomgba\gba_pane\ ^
  ..\blip_stub.c ..\mgba-gen\version.c || goto :fail
lib -nologo -out:mgba.lib ^
  mgba\src_arm\arm.obj mgba\src_arm\decoder-arm.obj mgba\src_arm\decoder.obj mgba\src_arm\decoder-thumb.obj ^
  mgba\src_arm\isa-arm.obj mgba\src_arm\isa-thumb.obj mgba\src_core\bitmap-cache.obj mgba\src_core\cache-set.obj ^
  mgba\src_core\cheats.obj mgba\src_core\config.obj mgba\src_core\core.obj mgba\src_core\directories.obj ^
  mgba\src_core\input.obj mgba\src_core\interface.obj mgba\src_core\library.obj mgba\src_core\lockstep.obj ^
  mgba\src_core\log.obj mgba\src_core\map-cache.obj mgba\src_core\mem-search.obj mgba\src_core\rewind.obj ^
  mgba\src_core\serialize.obj mgba\src_core\sync.obj mgba\src_core\thread.obj mgba\src_core\tile-cache.obj ^
  mgba\src_core\timing.obj mgba\src_gb\audio.obj mgba\src_gba\audio.obj mgba\src_gba\bios.obj ^
  mgba\src_gba\cheats.obj mgba\src_gba\core.obj mgba\src_gba\dma.obj mgba\src_gba\gba.obj ^
  mgba\src_gba\hle-bios.obj mgba\src_gba\input.obj mgba\src_gba\io.obj mgba\src_gba\memory.obj ^
  mgba\src_gba\overrides.obj mgba\src_gba\savedata.obj mgba\src_gba\serialize.obj mgba\src_gba\sharkport.obj ^
  mgba\src_gba\sio.obj mgba\src_gba\timer.obj mgba\src_gba\video.obj mgba\src_gba_cart\ereader.obj ^
  mgba\src_gba_cart\gpio.obj mgba\src_gba_cart\matrix.obj mgba\src_gba_cart\vfame.obj mgba\src_gba_cheats\codebreaker.obj ^
  mgba\src_gba_cheats\gameshark.obj mgba\src_gba_cheats\parv3.obj mgba\src_gba_renderers\cache-set.obj mgba\src_gba_renderers\common.obj ^
  mgba\src_gba_renderers\software-bg.obj mgba\src_gba_renderers\software-mode0.obj mgba\src_gba_renderers\software-obj.obj mgba\src_gba_renderers\video-software.obj ^
  mgba\src_gba_sio\gbp.obj mgba\src_gba_sio\joybus.obj mgba\src_util\circle-buffer.obj mgba\src_util\configuration.obj ^
  mgba\src_util\crc32.obj mgba\src_util\formatting.obj mgba\src_util\gbk-table.obj mgba\src_util\hash.obj ^
  mgba\src_util\string.obj mgba\src_util\table.obj mgba\src_util\vfs.obj mgba\src_util\convolve.obj ^
  mgba\src_util\export.obj mgba\src_util\patch.obj mgba\src_util\patch-fast.obj mgba\src_util\patch-ips.obj ^
  mgba\src_util\patch-ups.obj mgba\src_util\ring-fifo.obj mgba\src_util\text-codec.obj mgba\src_util_vfs\vfs-mem.obj ^
  mgba\src_util_vfs\vfs-fifo.obj mgba\src_util_vfs\vfs-fd.obj mgba\src_platform_windows\vfs-w32.obj mgba\src_platform_windows\memory.obj ^
  mgba\src_third_party_inih\ini.obj mgba\gba_pane\blip_stub.obj mgba\gba_pane\version.obj || goto :fail
cl -nologo -O2 -MT -W3 -std:c11 /Zc:preprocessor- %MGBA_DEFS% %INC% ..\gba-cc.c ..\cc_pad.c ..\cc_window.c mgba.lib ^
  -Fe"%OUT%\gba-cc.exe" user32.lib gdi32.lib xinput9_1_0.lib winmm.lib ws2_32.lib shlwapi.lib ole32.lib shell32.lib || goto :fail
popd
exit /b 0
:fail
set ERR=%ERRORLEVEL%
popd
exit /b %ERR%
