# Writes build.cmd (and mgba-gen/version.c) from mGBA's own CMake source
# lists, for a GBA-only, dependency-free, cl.exe-only build. Run it by hand
# after native/fetch_mgba.sh; its outputs are committed.
#   python native/gen_build.py
# The doom-pane gen_build.py pattern: parse upstream's list, emit one batch file.
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MGBA = os.path.join(HERE, 'mgba')
BS = chr(92)

COMMIT = '26b7884bc25a5933960f3cdcd98bac1ae14d42e2'
VERSION = '0.10.5'

# Upstream folders whose set(SOURCE_FILES ...) is built.
FOLDERS = ['src/arm', 'src/core', 'src/gba', 'src/util']

# In those lists but not built: the OpenGL renderer, PNG and ELF (no libpng, no libelf).
DROP = {'src/gba/renderers/gl.c', 'src/util/png-io.c', 'src/util/elf-read.c'}

# Not in those lists but built, as the root CMakeLists adds them on Windows:
# CORE_VFS_SRC (vfs-mem, vfs-fifo; vfs-fd and vfs-w32 on WIN32), OS_SRC
# (src/platform/windows/*.c) and THIRD_PARTY_SRC (inih). Then ours.
ADD = [
    'src/util/vfs/vfs-mem.c',
    'src/util/vfs/vfs-fifo.c',
    'src/util/vfs/vfs-fd.c',
    'src/platform/windows/vfs-w32.c',
    'src/platform/windows/memory.c',
    'src/third-party/inih/ini.c',
]
OURS = ['../blip_stub.c', '../mgba-gen/version.c']

DEFS = ('-DBUILD_STATIC -DM_CORE_GBA -DMINIMAL_CORE=1 -DDISABLE_THREADING -D_WIN32_WINNT=0x0600 -DNOMINMAX '
        '-DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_WARNINGS -DNDEBUG')
FLAGS = '-nologo -c -O2 -MT -std:c11 -W0 /MP /wd4003 /wd4244 /wd4146 /wd4267 /Zc:preprocessor-'
INC = '-I..' + BS + 'mgba-shim -I..' + BS + 'mgba' + BS + 'include -I..' + BS + 'mgba' + BS + 'src'


def cmake_sets(text):
    """Every set(NAME a b c) in a CMakeLists, as {NAME: [a, b, c]}."""
    out = {}
    for name, body in re.findall(r'set\((\w+)\s+([^)]*)\)', text):
        out[name] = body.split()
    return out


def source_files(folder):
    text = open(os.path.join(MGBA, folder, 'CMakeLists.txt')).read()
    sets = cmake_sets(text)
    files = []
    for item in sets['SOURCE_FILES']:
        m = re.fullmatch(r'\$\{(\w+)\}', item)
        files += sets[m.group(1)] if m else [item]
    return [os.path.normpath(os.path.join(folder, f)).replace(BS, '/') for f in files]


def main():
    sources = []
    for folder in FOLDERS:
        sources += [f for f in source_files(folder) if f not in DROP]
    sources += ADD
    seen = set()
    sources = [s for s in sources if not (s in seen or seen.add(s))]
    missing = [s for s in sources if not os.path.isfile(os.path.join(MGBA, s))]
    if missing:
        sys.exit('gen_build: missing from native/mgba: ' + ', '.join(missing))

    # version.c from upstream's template, its MPL header kept.
    template = open(os.path.join(MGBA, 'src/core/version.c.in')).read()
    values = {
        'GIT_COMMIT': COMMIT, 'GIT_COMMIT_SHORT': COMMIT[:7], 'GIT_BRANCH': VERSION, 'GIT_REV': '-1',
        'BINARY_NAME': 'mgba', 'PROJECT_NAME': 'mGBA', 'VERSION_STRING': VERSION,
    }
    version = re.sub(r'\$\{(\w+)\}', lambda m: values[m.group(1)], template)
    version = version.replace('#include <mgba/core/version.h>',
                              '/* Generated by gba-pane native/gen_build.py from src/core/version.c.in. */\n'
                              '#include <mgba/core/version.h>')
    os.makedirs(os.path.join(HERE, 'mgba-gen'), exist_ok=True)
    open(os.path.join(HERE, 'mgba-gen', 'version.c'), 'w', newline='\r\n').write(version)

    # One cl per source folder, each into its own object folder: several base
    # names repeat across folders (core.c, cheats.c, serialize.c, input.c,
    # cache-set.c, audio.c, memory.c).
    groups = {}
    for s in sources:
        groups.setdefault(os.path.dirname(s), []).append(s)
    groups['gba-pane'] = OURS
    compile_lines, mkdirs, objs = [], [], []
    for folder, files in groups.items():
        obj = 'mgba' + BS + folder.replace('/', '_').replace('-', '_')
        mkdirs.append(f'if not exist {obj} mkdir {obj}')
        paths = []
        for f in files:
            path = f if f.startswith('../') else 'mgba/' + f
            paths.append('..' + BS + path.replace('/', BS) if not path.startswith('../') else path.replace('/', BS))
            objs.append(obj + BS + os.path.splitext(os.path.basename(f))[0] + '.obj')
        chunks = [' '.join(paths[i:i + 6]) for i in range(0, len(paths), 6)]
        src = ' ^\n  '.join(chunks)
        compile_lines.append(f'cl %MGBA_FLAGS% %MGBA_DEFS% %INC% -Fo{obj}{BS} ^\n  {src} || goto :fail')
    obj_chunks = ' ^\n  '.join(' '.join(objs[i:i + 4]) for i in range(0, len(objs), 4))
    vcvars = BS.join(['C:', 'Program Files (x86)', 'Microsoft Visual Studio', '2022', 'BuildTools',
                      'VC', 'Auxiliary', 'Build', 'vcvars64.bat'])
    nl = '\n'

    cmd = f'''@echo off
rem Builds gba-cc.exe (mGBA 0.10.5, GBA core only) with MSVC into ..\\bin (or the folder given).
rem Generated by native\\gen_build.py from mGBA's CMake source lists; edit that, not this.
setlocal
set OUT=%~1
if "%OUT%"=="" set OUT=%~dp0..{BS}bin
rem A long inherited PATH overflows vcvars; start it from a clean one.
set "PATH=%SystemRoot%{BS}system32;%SystemRoot%;%ProgramFiles(x86)%{BS}Microsoft Visual Studio{BS}Installer"
call "{vcvars}" >nul || exit /b 1
if not exist "%~dp0obj" mkdir "%~dp0obj"
if not exist "%OUT%" mkdir "%OUT%"
pushd "%~dp0obj"
set MGBA_DEFS={DEFS}
set MGBA_FLAGS={FLAGS}
set INC={INC}
{nl.join(mkdirs)}
{nl.join(compile_lines)}
lib -nologo -out:mgba.lib ^
  {obj_chunks} || goto :fail
cl -nologo -O2 -MT -W3 -std:c11 /Zc:preprocessor- %MGBA_DEFS% %INC% ..{BS}gba-cc.c ..{BS}cc_pad.c ..{BS}cc_window.c mgba.lib ^
  -Fe"%OUT%{BS}gba-cc.exe" user32.lib gdi32.lib xinput9_1_0.lib winmm.lib ws2_32.lib shlwapi.lib ole32.lib shell32.lib || goto :fail
popd
exit /b 0
:fail
set ERR=%ERRORLEVEL%
popd
exit /b %ERR%
'''
    open(os.path.join(HERE, 'build.cmd'), 'w', newline='\r\n').write(cmd)
    print(f'gen_build: {len(sources)} mGBA sources + {len(OURS)} of ours, {len(groups)} folders -> build.cmd')


main()
